from .openai_imagenet_template import openai_imagenet_template
from .simple_template import simple_template
from .augment_template import *
from .imagenet_template import *
from .celeba_template import *
from .waterbirds_template import *
from .oxfordpets_template import *
from .cub200_template import *
from .food101_template import *
from .places365_template import *
from .flowers102_template import *
from .eurosat_template import *
